name = "pages-app"
compatibility_date = "2024-09-20"

[[d1_databases]]
binding = "DB"          # Env binding name used in code
database_name = "pages_app_db"
database_id = "local-dev" # For local dev this can be any string

