name = "jiuhuangweb3"
main = "functions/index.js"
compatibility_date = "2024-10-25"

[[d1_databases]]
binding = "DB"
database_name = "jiuhuangweb3"
<<<<<<< HEAD
database_id = "121c1dab-f829-4724-9fa7-2778ada03cdf"
=======
database_id = "b1ec34f4-17c2-406e-a094-0faff0b77597"
>>>>>>> 0a5aef1fd93d9f5b86f0ff6cbf6e97056d9520fc
