name = "jiuhuangweb3"
compatibility_date = "2024-10-25"

# 本地开发用的临时库（可保留/可改名）
[[d1_databases]]
binding = "DB"
database_name = "jiuhuangweb3"
database_id = "local-dev"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "jiuhuangweb3"
database_id = "b1ec34f4-17c2-406e-a094-0faff0b77597"  # 示例，换成实际 ID
