name = "jiuhuangweb3"
main = "functions/index.js"
compatibility_date = "2024-10-25"

[[d1_databases]]
binding = "DB"
database_name = "jiuhuangweb3"
database_id = "b1ec34f4-17c2-406e-a094-0faff0b77597"
