name = "jiuhuangweb3"
main = "functions/index.js"
compatibility_date = "2024-10-25"

[[d1_databases]]
binding = "DB"
database_name = "jiuhuangweb3"
database_id = "121c1dab-f829-4724-9fa7-2778ada03cdf"
